version: 0.2

env:
  exported-variables:
      - branch
phases:
  build:
    commands:
      - echo "Running Build Script..."
      - |-
          if [ "$branch" = "develop"  ]; then
            echo "Branch is develop"
            aws cloudformation validate-template --template-body file://templates/infra.json
          else
            echo "Branch is master"
            echo "Stack name is ${stack}"
           aws cloudformation deploy --template-file templates/infra.json --stack-name ${stack} --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
          fi
