version: 0.2

env:
  exported-variables:
      - branch
phases:
  build:
    commands:
      - echo "Running Build Script..."
      - |-
          if [ "$branch" = "develop"  ]; then
            echo "Branch is develop"
            node --check index.js
          else
            echo "Branch is master"
            echo "Stack name is ${stack}"
            ./deploy.sh
          fi
