AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  octankNewsAlexaLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: octankNewsAlexaLambda
      Description: Return
      Handler: function.handler
      CodeUri: ./function.py
      Runtime: python3.6
      MemorySize: 128
      Timeout: 30
      Role: !Ref ROLE
